### ISSUE TITLE
Code Generated by odatagen

### ISSUE THREAD

**Issue by John-Lluch** [OData/OData4ObjC#5]
Hi,

I still find compiler issues with the code generated by odatagen. See for instance these generated properties:

@property ( nonatomic , retain , getter=getaAlergenoPK , setter=setaAlergenoPK ) NSString *m_aAlergenoPK;
@property ( nonatomic , retain , getter=getaAlergenoPKO , setter=setaAlergenoPKO ) NSString *m_aAlergenoPKO;
@property ( nonatomic , retain , getter=getsLetraDominio , setter=setsLetraDominio ) NSString *m_sLetraDominio;

They still lack colons ':' after the setter names, so this code does not compile with the new compiler. This could be related with issue #3

Thanks.

**Comment by arlobelshee** [comment]
Dang. Looks like I missed some. I wish this code came with tests.

I will try to get a fix today.

Arlo

Sent from my Windows Phone

---

From: Joan-Lluch
Sent: 1/13/2012 3:57 AM
To: arlobelshee
Subject: [OData4ObjC] Code Generated by odatagen (#5)

Hi,

I still find compiler issues with the code generated by odatagen. See for instance these generated properties:

@property ( nonatomic , retain , getter=getaAlergenoPK , setter=setaAlergenoPK ) NSString *m_aAlergenoPK;
@property ( nonatomic , retain , getter=getaAlergenoPKO , setter=setaAlergenoPKO ) NSString *m_aAlergenoPKO;
@property ( nonatomic , retain , getter=getsLetraDominio , setter=setsLetraDominio ) NSString *m_sLetraDominio;

They still lack colons ':' after the setter names, so this code does not compile with the new compiler. This could be related with issue #3

Thanks.

---

Reply to this email directly or view it on GitHub:
https://github.com/OData/OData4ObjC/issues/5

**Comment by arlobelshee** [comment]
There's a particular piece of stupid in this application which may be biting you. Can you try something for me and tell me whether it fixes your problem? Your answer will help me figure out what's broken so that I can fix it for real (it might also resolve the issue for you so that you can carry on with life).

odatagen doesn't use resource files. Instead it depends on a certain set of XSLT files being located right next to the application when it runs. If those aren't there, then it tries to copy them out of the source tree. It knows the places to which it is commonly built, and attempts to navigate from there to the source and copy a set of files. Downright dumb, but there you go.

If it already has those files lying around, then it skips the copy. And those files were a big part of what I had to fix to get the colons on the setters.

So, can you delete *.xsl from the directory that contains the odatagen you are running? Run it again and tell me what happens.

If you are just running into cached bad versions of those files, then everything should work for you, and I just need to fix the stupid (eg, bundle these as resources).

If I've missed a setter (and I've now looked several times), then things will still be broken for you. That'll tell me to look even closer for more code gen.

Thanks for your help debugging this.

**Comment by John-Lluch** [comment]
Thanks for your quick reply. Eventually, I am not having access to the OData server I use for testing in the next few days, so I am not able to regenerate the files until I can reach it again. As soon as I can connect again and am able to try what you suggest I will let you know how it goes . Thanks again !

**Comment by John-Lluch** [comment]
Ok, so I finally got a chance to access our testing OData service. I did what you suggested, i.e. I deleted all the xsl files on the odatagen directory and ran the utility again. It worked!. The files were generated as they should with the colons after the setter methods. The default LLVM 3.0 compiler parsed them like a charm, and so far everything is going well. Thank you very much !
