### ISSUE TITLE
ODataEntity.h: Method name referenced in property setter attribute must end with ':'

### ISSUE THREAD

**Issue by ozba** [OData/OData4ObjC#9]
Hi,
I can see that teeqemm opened this issue 3 months ago:
https://github.com/OData/OData4ObjC/issues/3
and arlobelshee closed it as fixed.

But I downloaded the code, added the framework from 
OData4ObjC / Framework / bin / odatalib / lib / iPhoneSimulatorLibs / iPhone_Simulator_4.3 / release / libMSODataLib.a
in xcode 4.2.1, ios deployment target 4.3
and again got these exceptions:
"Method name referenced in property setter attribute must end with ':'".

What should I do?
Thanks

**Comment by ndicenso** [comment]
I recently downloaded the code added the framework and encountered the same issue. It looks like the code has been fixed and updated in the source files but not updated in the framework binaries or odatagen. @arlobelshee are you guys planning on updating the included odatagen as well?

**Comment by arlobelshee** [comment]
Sorry about that.

Yes, I should update the binaries. I will try to get to that in the next few days.

Arlo

**Comment by ndicenso** [comment]
@arlobelshee After further inspection of the files included in the sdk, I noticed that the binaries do not actually need to be updated. Just a copy of the updated xsl files must be added to the location of the binary. Since the parsing logic is abstracted in the xsl files, updating those file will do the trick. No binary update required. However, once I updated those xsl files in the correct odatagen folder for my build I began getting errors related to base classes. I am going to look and se if this is already a known issue before I post a new issue. It appears that the base class includes the full service namespace like namespace_baseClass. but classes that inherit from that class only get the name namespace_subClass:baseClass. It should be namespace_subClass: namespace_baseClass.

This appears to be easily fixed by updating objc_headers.xsl line 37 to include: <xsl:value-of select="$modified_service_namespace"/>_ when the base class is not oDataObject. I have tested this fix in a limited capacity with successfjul regeneration of proxy classes and data retrieval against oData Service.

Thanks,
Noah

**Comment by joeamu** [comment]
@ndicenso Could you possibly post your fix? I have the same problem after upgrading to Lion and Xcode 4.

Thanks,
Joe

**Comment by ndicenso** [comment]
@arlobelshee has there been any update in this issue? I am still working with my local versions of the xslt files. I would like to stay current with the latest files form github.

**Comment by ndicenso** [comment]
@joeamu Sorry for not getting back to you sooner. I am not sure the best way to post the fix. I don't know if pasting it in here is the best approach. I am happy to email you the changed files or post them somewhere.

**Comment by sellingsolutions** [comment]
@ndicenso Could you please upload your fix? Either to pastebin or whatever you prefer using. I would really appreciate it, thank you in advance!
PS. If you prefer to send me an email : alexander@sellingsolutions.se

**Comment by ndicenso** [comment]
@sellingsolutions I uploaded files this morning to a fork to fix this. I also created a pull request to try and get these changes integrated into the existing code base. see issue #11 for more info

**Comment by ndicenso** [comment]
Alexander,

I updated the issue this morning with some more details and added the
changed files to a fork/pull request. I hope this helps.

Let me know if you have any issues.

Thanks,
Noah

On Mon, Jun 25, 2012 at 7:43 AM, sellingsolutions <
reply@reply.github.com

**Comment by sellingsolutions** [comment]
@ndicenso Thanks!

**Comment by sellingsolutions** [comment]
@ndicenso It works wonderfully! What a time saver! Thanks a bunch!

The only thing your code missed was the very bottom of the file, the part that seems to be related to my DbContext file on the C#.NET side in my WCF Data Service.

The properties belonging to the class :

/**
- Container interface InspectionnaireEntities, Namespace: InspectionnaireModel
  */
  @interface InspectionnaireEntities : ObjectContext
  {
   NSString *m_OData_etag;
   DataServiceQuery *m_C__MigrationHistory;
  }
  @property ( nonatomic , retain , getter=getEtag , setter=setEtag )NSString *m_OData_etag;
  @property ( nonatomic , retain , getter=getC__MigrationHistory , setter=setC__MigrationHistory ) DataServiceQuery *m_C__MigrationHistory;

I've omitted my own properties, but these properties should be mutual for all developers(then again I'm a complete noob so I'm probably wrong)

The ':' is missing in the declaration of these properties but ONLY in this class, which as is, is just a wonderful time saver. Typing in that semi colon 20 times for my own properties is nothing compared to a 1000 :P

Thanks again!

**Comment by arlobelshee** [comment]
I've integrated @ndicenso's pull request. Thank you @ndicenso!

**Comment by gaurangtalwadkar** [comment]
Hey I am still facing the issue. 
mProperties.h : Method name referenced in property setter attribute must end with ':'

Please let me know how to fix it..
